spring:
  hello:
    name: Myolnir All
logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: TRACE
    
endpoints:
  restart:
    enabled: true
