server:
  port: 1234
spring:
  hello: 
    name: Myolnir Production
logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: ERROR
    org.springframework.web: ERROR
endpoints:
  restart:
    enabled: true
