server:
  port: 1234
spring:
  hello:
    name: Myolnir Production changed by RefreshScope
logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: ERROR
    org.springframework.web: ERROR
